### ISSUE TITLE
JSON parsing error in Download class prevents contest data retrieval

### ISSUE THREAD

**Issue by ShinniUwU** [Borovaneca/JudgeFileGenerator#1]
Description:
The application encounters an error when attempting to parse the JSON response in the Download class. This error occurs silently, allowing the application to continue running but preventing any meaningful action from taking place. The issue is particularly noticeable when running the application as a JAR file on Linux systems.

Error message (when run with java -jar):
```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because "jsonElement" is null
    at kong.unirest.json.JSONObject.<init> (JSONObject.java:85)
    at kong.unirest.json.JSONObject.<init> (JSONObject.java:55)
    at service.Download.download (Download.java:31)
    at service.Login.lambda$run$1 (Login.java:96)
    at java.lang.Thread.run (Thread.java:840)
```

Steps to reproduce:
1. Run the application (particularly as a JAR file on Linux)
2. Attempt to download contest information
3. The application continues running but no files are created or downloaded

Expected behavior:
The application should successfully parse the JSON response and proceed with creating the necessary files.

Actual behavior:
The application silently fails to parse the JSON, continuing to run without creating any files or showing any visible errors to the user.

Suggested actions:
1. Add logging to print out the raw response body before attempting to parse it
2. Implement more robust error handling and null checks in the Download class
3. Consider using a different JSON parsing library if the issue persists
4. Verify the API response format and ensure it matches the expected structure
5. Implement a mechanism to save login credentials in a JSON file to avoid repeated logins
6. Investigate Linux-specific issues, particularly related to running the application as a JAR file
7. Add a visible error message or log for the user when JSON parsing fails

Additional feature request:
Implement a feature to save login credentials securely in a JSON file, allowing users to avoid logging in every time they use the application.

Platform-specific note:
The application currently doesn't work properly on Linux when run as a JAR file. This may be related to Wine not allowing copy-pasting. Further investigation into Linux compatibility is needed.

Priority: High
Severity: Major

Additional notes:
While this issue doesn't crash the application, it prevents its core functionality from working, especially on Linux systems. Addressing this issue and improving cross-platform compatibility should be a high priority.

**Comment by Borovaneca** [comment]
Thank you for bringing this issue to our attention. I have have successfully resolved the problem and added the requested feature in the latest update.

### Key Updates:

1. **Bug Fix**:
- The **NullPointerException** related to JSON parsing in the `Download` class has been fixed. The application now handles null values gracefully, and appropriate error messages will be displayed if the JSON response does not meet the expected structure.

2. **New Feature**:
- I have implemented a feature to **save login credentials** securely in a JSON file located in the user's home directory. This will allow you to avoid repeated logins, improving the user experience. If the login fails, the credentials will be automatically cleared.

**Comment by Borovaneca** [comment]
Please take some time to test the new updates, and feel free to provide any suggestions or report any bugs. The issue will remain open until I receive a positive confirmation from you after using the application. Looking forward to your feedback.

**Comment by ShinniUwU** [comment]
the document is still 0 bytes with nothing inside here's a video 

https://github.com/user-attachments/assets/a02ea019-2ab7-4016-a4c5-6da527bfbafe

**Comment by Borovaneca** [comment]
Did you have permissions to download the file with the current login user? You can find out when you try to download the file from your browser and if you get :
![image](https://github.com/user-attachments/assets/18fa7acd-f041-4886-89f3-d23e43b9690f)
you will not be abble to download it from the application (empty file).

**Comment by ShinniUwU** [comment]
sorry for the late response I do have access yes

**Comment by ShinniUwU** [comment]
at least at the time now I don't

**Comment by ShinniUwU** [comment]
I just tried with another contest where I have access and its the same result

**Comment by Borovaneca** [comment]
Its strange.. on me its working.. idk what is the problem.. -.- make some video please .. or some screenshots. Thank you.
